"use client";
import { useEffect, useState } from "react";
import { Plus, Search, Trash2 } from "lucide-react";
import { add, getAll, remove } from "@/lib/db";
import { formatCurrency } from "@/lib/utils";
export default function StockPage() {
  const [products, setProducts] = useState<any[]>([]); const [search, setSearch] = useState("");
  const load = () => setProducts(getAll<any>("products")); useEffect(() => { load(); }, []);
  const createProduct = () => { add<any>("products", { name: `Produit ${products.length + 1}`, barcode: "", category: "Divers", purchasePrice: 100, salePrice: 150, quantity: 10, lowStockThreshold: 5, tvaRate: 19 }); load(); };
  return <div className="space-y-4"><div className="flex justify-between gap-3"><h2 className="text-lg font-semibold">Stock / Inventaire</h2><button onClick={createProduct} className="flex items-center gap-2 px-4 py-2 rounded-lg bg-primary text-white text-sm font-medium"><Plus size={16} /> Nouveau produit</button></div><div className="relative max-w-sm"><Search size={16} className="absolute top-1/2 -translate-y-1/2 left-3 text-gray-400" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Rechercher..." className="w-full pl-9 pr-3 py-2 rounded-lg border border-gray-200 text-sm" /></div><div className="card overflow-x-auto p-0"><table className="w-full text-sm"><thead className="bg-gray-50 text-gray-500 text-xs uppercase"><tr><th className="text-left px-4 py-3">Nom</th><th className="text-left px-4 py-3">Catégorie</th><th className="text-right px-4 py-3">Prix vente</th><th className="text-right px-4 py-3">Qté</th><th className="text-right px-4 py-3">Actions</th></tr></thead><tbody>{products.filter((p)=>p.name.toLowerCase().includes(search.toLowerCase())).map((p)=><tr key={p.id} className="border-t border-gray-50"><td className="px-4 py-3 font-medium">{p.name}</td><td className="px-4 py-3 text-gray-500">{p.category}</td><td className="px-4 py-3 text-right">{formatCurrency(p.salePrice)}</td><td className="px-4 py-3 text-right">{p.quantity}</td><td className="px-4 py-3 text-right"><button onClick={() => { remove('products', p.id); load(); }} className="text-gray-500 hover:bg-gray-100 p-1.5 rounded"><Trash2 size={16} /></button></td></tr>)}</tbody></table></div></div>;
}
